DreamDay/Controllers/AdminController.cs
using DreamDay.Entites;
using DreamDay.Models;
using DreamDay.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DreamDay.Controllers
{
    public class AdminController : Controller
    {

        private readonly AdminService _adminService;

        public AdminController(AdminService adminService)
        {
            _adminService = adminService;
        }

        public async Task<IActionResult> Vendors()
        {
            var vendors = await _adminService.GetVendors();
            return View(vendors);
        }

        public IActionResult AddVendor() => View();

        [HttpPost]
        public async Task<IActionResult> AddVendor(VendorModel vendor)
        {
            if (!ModelState.IsValid) return View(vendor);
            await _adminService.AddVendor(vendor);
            return RedirectToAction("Vendors");
        }


        public async Task<IActionResult> EditVendor(Guid id)
        {
            var vendor = await _adminService.GetVendorById(id);
            return vendor == null ? NotFound() : View(vendor);
        }

        [HttpPost]
        public async Task<IActionResult> EditVendor(VendorModel vendor)
        {
            if (!ModelState.IsValid) return View(vendor);
            await _adminService.UpdateVendor(vendor);
            return RedirectToAction("Vendors");
        }

        public async Task<IActionResult> DeleteVendor(Guid id)
        {
            await _adminService.DeleteVendor(id);
            return RedirectToAction("Vendors");
        }

        public async Task<IActionResult> Dashboard()
        {
            var stats = await _adminService.GetAdminDashboardStatsAsync();
            ViewBag.UserCount = stats.Item1;
            ViewBag.CoupleCount = stats.Item2;
            ViewBag.PlannerCount = stats.Item3;
            ViewBag.VendorCount = stats.Item4;
            return View();
        }

        public async Task<IActionResult> AssignPlanner()
        {
            var weddings =  await _adminService.GetAllWeddingsWithoutPlannerAsync();
            return View(weddings);
        }


        public async Task<IActionResult> Assign(Guid weddingId)
        {
            var planners = await _adminService.GetPlannersListsAsync(weddingId);

            ViewBag.Planners = planners.Select(s=> new SelectListItem { Value = s.Id.ToString(), Text = s.Name }).ToList();
            ViewBag.WeddingId = weddingId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(Guid weddingId, Guid plannerId)
        {
            await _adminService.AssignPlannerToWeddingAsync(weddingId, plannerId);

            return RedirectToAction("AssignPlanner");
        }
    }
}

DreamDay/Controllers/BudgetController.cs
using DreamDay.Entites;
using DreamDay.Models;
using DreamDay.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace DreamDay.Controllers
{
    [Authorize(Roles = "COUPLE")]
    public class BudgetController : Controller
    {
        private readonly BudgetService _budgetService;

        public BudgetController(BudgetService budgetService)
        {
            _budgetService = budgetService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);

            var data = await _budgetService.GetListAsync(userId);
            if(data == null)
            {
                return RedirectToAction("Create", "Wedding");
            }

            ViewBag.TotalBudget = data.Value.Item2;
            ViewBag.TotalAllocated = data.Value.Item1.Sum(x => x.AllocatedAmount);
            ViewBag.TotalSpent = data.Value.Item1.Sum(x => x.SpentAmount);

            return View(data.Value.Item1);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BudgetItemModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var data = await _budgetService.CreateAsync(userId, model);
            if (data == null) return RedirectToAction("Create", "Wedding");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var data = await _budgetService.GetBudgetItemAsync(id);
            if (data == null) return NotFound();
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BudgetItemModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var data = await _budgetService.UpdateAsync(model);
            if (data == null)
                return NotFound();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _budgetService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

DreamDay/Controllers/GuestController.cs
using DreamDay.Entites;
using DreamDay.Enums;
using DreamDay.Models;
using DreamDay.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace DreamDay.Controllers
{
    [Authorize(Roles = "COUPLE")]
    public class GuestController : Controller
    {
        private readonly Services.GuestService _guestService;

        public GuestController(GuestService guestService)
        {
            _guestService = guestService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);

            var data = await _guestService.GetListAsync(userId);

            if(data == null)
                return RedirectToAction("Index", "Wedding");

            return View(data);
        }

        [HttpGet]
        public IActionResult Create() {

            ViewBag.MealOptions = new SelectList(Enum.GetValues(typeof(MealPreference)));
            return View();

        }


        [HttpPost]
        public async Task<IActionResult> Create(GuestModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var userId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
            var data = await _guestService.AddAsync(userId, model);

            if(data == null)
                return RedirectToAction("Index", "Wedding");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            ViewBag.MealOptions = new SelectList(Enum.GetValues(typeof(MealPreference)));
            var data = await _guestService.GetByIdAsync(id);
            if (data == null) return NotFound();
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GuestModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var data = await _guestService.UpdateAsync(model);
            if (data == null) return NotFound();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _guestService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

DreamDay/Controllers/VendorController.cs
using DreamDay.Entites;
using DreamDay.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace DreamDay.Controllers
{
    [Authorize(Roles = "COUPLE")]
    public class VendorController : Controller
    {
        private readonly Services.VendorService _vendorService;

        public VendorController(VendorService vendorService)
        {
            _vendorService = vendorService;
        }

        public async Task<IActionResult> Index(string? search)
        {
            var weddingId = await _vendorService.GetWeddingIdByUser(Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!));

            if (weddingId == null)
            {
                return RedirectToAction("Create", "Wedding");
            }

            ViewBag.WeddingId = weddingId;
            ViewBag.Search = search;

            var assaginedVendors = await _vendorService.GetAssginedVendorForWeddingAsync((Guid)weddingId);
            var availableVendors = await _vendorService.GetAvailableVendorsAsync((Guid)weddingId, search);

            return View(Tuple.Create(assaginedVendors, availableVendors));
        }


        [HttpPost]
        public async Task<IActionResult> Assign(Guid weddingId, Guid vendorId)
        {

            await _vendorService.AssignVendorToWeddingAsync(weddingId, vendorId);

            return RedirectToAction("Index", new { weddingId });
        }


        [HttpPost]
        public async Task<IActionResult> Remove(Guid weddingId, Guid vendorId)
        {
            await _vendorService.RemoveVendorFromWeddingAsync(weddingId, vendorId);
            return RedirectToAction("Index", new { weddingId });
        }
    }
}

DreamDay/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using DreamDay.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DreamDay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DreamDay.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
</head>
<body>
    <header>

        @{
            var userRole = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value;
        }

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (userRole == Role.COUPLE.ToString())
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">DreamDay</a>
                }
                else
                {

                     <a class="navbar-brand" asp-area="" asp-controller="Planner" asp-action="Dashboard">DreamDay</a>
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @if(User.Identity?.IsAuthenticated ?? false)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @if (userRole == Role.COUPLE.ToString())
                            {
                            
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Guest" asp-action="Index">Guest</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Budget" asp-action="Index">Budget Tracker</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Checklist" asp-action="Index">Checklist</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Vendor" asp-action="Index">Vendors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CoupleTimeline" asp-action="Index">Timeline management</a>
                                </li>
                            
                            }
                            else if(userRole == Role.PLANNER.ToString())
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Planner" asp-action="Dashboard">Planner Dashboard</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="PlannerReports" asp-action="TopVendors">Top Vendors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="PlannerReports" asp-action="AverageBudget">Average Budget</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="PlannerReports" asp-action="VendorCategoryDistribution">Vendor Categories</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="PlannerReports" asp-action="ChecklistProgressReport">Checklist Progress Report</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="Dashboard">Admin Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="AssignPlanner">Assign Planner</a>
                                </li>
                            }

                        </ul>

                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <span class="nav-link">👤 @User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        </ul>

                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DreamDay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>